before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: i6kxWMmhPDAW737polT9SNiw9j4psR89Daxj34Wweh/5tKYbz2LQgFPs/QUbeCy2o8JEG+AcEI7C9HkMOqPnSzpLggLWcXGHeH/T16aMOvRK7iSDC0F3uHFmfDMP/FmJQShkWqjsyBcJ+m4N+c8QyD0tAZKrBRn6G07pjrNcEA4mTee/00FJkLC6dY3aRTyjeDXAaCdzCj+iGtGiHVf/wv3NKo9TVqqRm01YJ3eSnnE14mIzt2oDj7uxrYa3wY6FOzFhE3GI+THhFs+O34yVM+Wy6LJr7tekdC+Ji5gOX494PVO9cJ/VsLCpkwdyI7QLG03EQaBdzkQdIPIMKfD7/tyTcgn6IWYSC0tDSkMYpTrnN/zFtosDeCPLccEFmrUJ7Z3U1TI1i83AdVqGz+7ao4pIXuukwLaOgcV8stsLC8chZM8cNLkSOm0VSfmti2+/sLdjSptq6NLp+FTJHp44g9f8CxAAfEGboIIBQwNQ6rrNPRD3JqsfB2KZ8M0l/oBWEySHvgvoOMRSRD3CKmpLDzqCyH147IK69aVl+pZbOZvJtWgruJUcfK3LLxT4RyPNe8wt7wWtR+TwiCCuvvnvaSAOW4B98iMYLxPPlShKjb1pHCnCOJnvXuI3ThJM2T2JNthSm/7xw45VlCCIA0vP5r7+btQMWq3lF/30Lt55YM0= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
